baseurl = "https:/containo.us/"
languageCode = "en-us"
title = "Containous"

[params]
  # description = "Container delivery company"
  author = "Emile Vauge"
  github = "containous"
  twitter = "emilevauge"
  logo = "/containous.logo.png"
  mainIcon = "/containous.logo.tiny.png"
  cover = "/cover.jpg"
  email = "contact@containo.us"
